VideoApp.WEB.User/Controllers/VideoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VideoApp.BL.BLModels;
using VideoApp.BL.DALModels;
using VideoApp.BL.Mapping;
using VideoApp.BL.Repositories;
using VideoApp.WEB.User.ViewModels;

namespace VideoApp.WEB.User.Controllers
{
    [Authorize]
    public class VideoController : Controller
    {
        private readonly RwaMoviesContext _dbContext;
        private readonly IVideoRepository _videoRepository;
        private readonly IMapper _mapper;                

        public VideoController(RwaMoviesContext dbContext, IVideoRepository videoRepository, IMapper mapper)
        {
            _dbContext = dbContext;
            _videoRepository = videoRepository;
            _mapper = mapper;
        }

        public ActionResult Index(string filter, int page, int size, string orderBy, string? direction)
        {

            if (size == 0)
                size = 6;

            (var pagedVideos, var unpagedCount) = _videoRepository.GetPagedVideos(filter, page, size, orderBy, direction);

            var vmVideos = _mapper.Map<IEnumerable<VMVideo>>(pagedVideos);

            foreach (var vmVideo in vmVideos)
            {
                var dalImage = _dbContext.Images.FirstOrDefault(x => x.Id == vmVideo.ImageId);
                if (dalImage != null)
                {
                    vmVideo.ImageURl = dalImage.Content;
                }
            }

            ViewData["page"] = page;
            ViewData["size"] = size;
            ViewData["orderBy"] = orderBy;
            ViewData["direction"] = direction;
            ViewData["pages"] = (int)Math.Ceiling((double)unpagedCount / size);

            ViewData["videos"] = vmVideos;

            return View();
        }

        //public ActionResult GetFilteredVideos(string filter)
        //{
        //    var filteredVideos = _videoRepository.GetFilteredVideos(filter);

        //    var vmVideos = _mapper.Map<IEnumerable<BLVideo>>(filteredVideos);

        //    ViewData["page"] = filter;

        //    return PartialView("_VideoPartial", vmVideos);
        //}

        public ActionResult VideoPartial(string filter, int page, int size, string? orderBy, string? direction)
        {
            if (size == 0)
                size = 6;

            (var pagedVideos, var unpagedCount) = _videoRepository.GetPagedVideos(filter, page, size, orderBy, direction);

            var vmVideos = _mapper.Map<IEnumerable<VMVideo>>(pagedVideos);



            foreach (var vmVideo in vmVideos)
            {
                var dalImage = _dbContext.Images.FirstOrDefault(x => x.Id == vmVideo.ImageId);
                if (dalImage != null)
                {
                    vmVideo.ImageURl = dalImage.Content;
                }
            }
                        

            ViewData["filter"] = filter;
            ViewData["page"] = page;
            ViewData["size"] = size;
            ViewData["orderBy"] = orderBy;
            ViewData["direction"] = direction;
            ViewData["pages"] = (int)Math.Ceiling((double)unpagedCount / size);

            ViewData["videos"] = vmVideos;

            return PartialView("_VideoPartial");
        }



        // GET: VideoController/Details/5
        public ActionResult Details(int id)
        {
            
            var dalVideos = _dbContext.Videos.Include("Genre")
                                            .Include("VideoTags")
                                            .Include("VideoTags.Tag")
                                            .Include("Image")
                                            .FirstOrDefault(x => x.Id == id);

            //Validacija:
            if (dalVideos == null)
            {
                return NotFound("Video not found!");
            }

            var blVideo = VideoMapper.MapToBl(dalVideos);

            var vmVideos = _mapper.Map<VMVideo>(blVideo);


            // Naziv žanra:
            vmVideos.GenreName = dalVideos.Genre.Name;

            // Url slike:
            if (dalVideos.Image != null && dalVideos.Image.Content != null)
            {
                vmVideos.ImageURl = dalVideos.Image.Content;
            }

            return View("Details", vmVideos);
        }
    }
}

VideoApp.WEB.User/Views/Video/Details.cshtml
@model VideoApp.WEB.User.ViewModels.VMVideo

@{
    ViewData["Title"] = "Details";
}

<div class="divCenter">
    <h1>@Model.Name</h1>

    <div class="main">
        <br />
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Description)
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.GenreName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.GenreName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.TotalTime)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TotalTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StreamingUrl)
            </dt>
            <dd class="col-sm-10">
                @if (!string.IsNullOrEmpty(Model.StreamingUrl))
                {
                    <a href="@Model.StreamingUrl" target="_blank">@Model.StreamingUrl</a>
                }
                else
                {
                    <span>No streaming URL available</span>
                }
            </dd>
            <div class="services-img-window">
                @if (Model.ImageURl != null)
                {
                    <img src="~/Images/@Model.ImageURl" class="card-img-top img-fluid img-small">
                }
                else
                {
                    <img src="https://media.istockphoto.com/id/1276906195/vector/camera-movie-logo-vector.jpg?s=170667a&w=0&k=20&c=7pdtVQHAkpdU_TFhqN7orAXrw-2rNFhhTfS-Gt0uoBA=" class="card-img-top img-fluid img-small">
                    //<span>No image available</span>
                }
            </div>
            <div class="mt-3">
                <a class="btn" href="@Model.StreamingUrl">Play video</a>
            </div>
        </dl>
    </div>
    <div>
        <a class="btnBack" asp-action="Index">Back to Gallery</a>
    </div>
</div>

<style>
    .img-small {
        max-height: 150px;
        width: auto;
    }

</style>

VideoApp.WEB.User/Views/Video/Index.cshtml
@using VideoApp.WEB.User.ViewModels;

@{
    List<VMVideo> videos = ViewData["videos"] as List<VMVideo>;
    int numRows = 2;
    //int cardsPerRow = videos.Count / numRows;
    //int cardsPerRow = 3;
    int cardsPerRow = Math.Max(videos.Count / numRows, 1);

    var page = (int)ViewData["page"];
    var pages = (int)ViewData["pages"];
    var size = (int)ViewData["size"];
    var orderBy = (string)ViewData["orderBy"];
    var direction = (string)ViewData["direction"];
}
<section>
    <header class="text-center">
        <h2 class="alert">Video Gallery</h2>
        <p></p>
    </header>

    <form method="get" action="@Url.Action("Index")">
        <div class="form-group col-4">
            <label for="filter">Search video:</label>
            <input type="text" class="form-control" name="filter" id="filter" value="@ViewBag.Filter">
        </div>
        <button type="submit" class="btn mt-3 mb-4">Search</button>
    </form>
          
    <div id="videosPart" class="container">

        <partial name="_VideoPartial" />
    </div>

<div class="btn-group">
@for (int i = 0; i < pages; i++)
    {
            var currClass = page == i ? "btn-light" : "btn btn-outline-light";
            <a asp-action="Index" 
               asp-route-page="@i" 
               asp-route-size="@size"
               asp-route-orderBy="@orderBy"
               asp-route-direction="@direction"
               data-page="@i"
               class="pager-btn btn @currClass">@(i + 1)</a>
    }

</div>
</section>

@section Scripts{
    <script>
        $(".pager-btn").click(function (event) {
            console.log("Pager button clicked");
            event.preventDefault();

            // No data was sent to the server, that's why we always get the first page
            // Let's fix that
            var page = $(this).data("page");

            var ajaxData = {
                page: page,
                size: @size,
                orderBy: "@orderBy",
                direction: "@direction",                
            }

            $.ajax({
                type: "GET",
                url: "/Video/VideoPartial",
                data: ajaxData,
                success: function (data) {
                    $("#videosPart").html(data);

                    //selected page number:
                    $(".pager-btn").removeClass("btn-light");
                    $(".pager-btn").addClass("btn-outline-light");

                    $(".pager-btn[data-page=" + page + "]").removeClass("btn-outline-light");
                    $(".pager-btn[data-page=" + page + "]").addClass("btn-light");
                },
                error: function (data) {
                    console.error("Ajax GET error", data);
                }
            });
        });
    </script>
}

VideoApp.WEB.User/Views/Video/_VideoPartial.cshtml
@using VideoApp.WEB.User.ViewModels;
@model IEnumerable<VideoApp.WEB.User.ViewModels.VMVideo>

@{
    List<VMVideo> videos = ViewData["videos"] as List<VMVideo>;
    int numRows = 2;
    //int cardsPerRow = videos.Count / numRows;
    ////int cardsPerRow = 3;
    int cardsPerRow = Math.Max(videos.Count / numRows, 1);  
}

@functions {
    public string ConvertSeconds(int totalSeconds)
    {
        int hours = totalSeconds / 3600;
        int minutes = (totalSeconds % 3600) / 60;
        return $"{hours}h {minutes}m";
    }
}

@for (var i = 0; i < numRows; i++)
{
    <div class="row p-2 justify-content-around">
        @foreach (var video in @videos.Skip(i * cardsPerRow).Take(cardsPerRow))
        {
            <div class="card col-3 m-3 services-card">
                <div class="services-img-window img-center">
                    @if (video.ImageId != null)
                    {
                        <img src="~/Images/@video.ImageURl" class="card-img-top img-fluid img-small">
                    }
                    else
                    {
                        @*<img src="/Images/movies.jpg" class="card-img-top img-fluid img-small">*@
                        <img src="/Images/filmKamera.jpg" class="card-img-top img-fluid img-small">
                    }

                </div>
                <div class="card-body">
                    <h3 class="card-title">@video.Name</h3>
                    <p class="card-text">@video.Description</p>
                    <a class="btn" href="@Url.Action("Details", "Video", new { id = video.Id })">Details</a>

                </div>
            </div>
        }
   </div>
}